Slack-Client:
    i40_alert: "xoxb-573436606260-4613742840116-WuC4mAOt928FmpJgxyhkpYFY"

Mysql-i40nc:
    dbname: "i40ncv1"
    user: "dbadmin"
    pwd: "mYsql?945"
    uri: "localhost"
    port: "3306"


